In [1]:
# importing libraries
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler 

In [2]:
#loading train data
fashion_train = pd.read_csv(r"D:\Fall 2020 courses\CSC5825 machine learning\homework\HW3\fashion-mnist_train.csv")
fashion_train.head(5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
#loading test data
fashion_test = pd.read_csv(r"D:\Fall 2020 courses\CSC5825 machine learning\homework\HW3\fashion-mnist_test.csv")
fashion_test.head(5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
# dimensionality of train data
fashion_train.shape

(60000, 785)

In [5]:
# dimensionality of test data
fashion_test.shape

(10000, 785)

In [6]:
# defining features and classes for train data
traindata = fashion_train.iloc[:,1:]
trainlabel = fashion_train.label
label = sorted(trainlabel.unique())

In [7]:
traindata.shape

(60000, 784)

In [8]:
trainlabel.shape

(60000,)

In [9]:
# defining features and classes for test data
testdata = fashion_test.iloc[:,1:]
testlabel = fashion_test.label
label = sorted(testlabel.unique())

In [10]:
testdata.shape

(10000, 784)

In [11]:
testlabel.shape

(10000,)

In [12]:
# Initialising the Scaler
scaler = StandardScaler() 

In [13]:
# To scale data 
scaler.fit(traindata,testdata)

StandardScaler()

In [14]:
traindata = scaler.fit_transform(traindata)
testdata = scaler.fit_transform(testdata)

In [15]:
# defining Singular Value Decomposition, taking n_components to be 140
svd = TruncatedSVD(n_components=140, n_iter=10, random_state=50)

In [16]:
svd.fit(traindata,testdata)

TruncatedSVD(n_components=140, n_iter=10, random_state=50)

In [17]:
traindata = svd.fit_transform(traindata)
testdata = svd.fit_transform(testdata)



In [18]:
# Variance ratio
print(svd.explained_variance_ratio_)

[0.2203887  0.14443455 0.05489046 0.05045265 0.03989157 0.0301118
 0.02799255 0.02262399 0.01738288 0.01395345 0.01195037 0.00968542
 0.00956136 0.00883147 0.00818406 0.00722294 0.00699141 0.0064383
 0.00621224 0.0061593  0.00561234 0.00514548 0.00483003 0.00466102
 0.00456989 0.00437004 0.00421757 0.00403266 0.00391759 0.00378978
 0.00363054 0.00353005 0.00336982 0.00334469 0.0033021  0.00316424
 0.00309688 0.00302337 0.00293495 0.00275741 0.0027244  0.0026558
 0.00259824 0.00257382 0.00248396 0.00241001 0.00234644 0.00226676
 0.00223933 0.00217288 0.00215556 0.0020891  0.00204174 0.00201352
 0.00195905 0.00190188 0.00188707 0.00181556 0.00178303 0.00173938
 0.00171479 0.00170364 0.00169611 0.00168592 0.00162656 0.00160845
 0.0015679  0.00154899 0.00151699 0.00149675 0.00148472 0.00144578
 0.00141687 0.00137962 0.00136874 0.00133498 0.00132835 0.00130612
 0.00129799 0.00127524 0.00127184 0.0012381  0.0012298  0.00119971
 0.00118841 0.00117683 0.00115572 0.00112014 0.00111393 0.0010859

In [19]:
# total variance ratio
print(svd.explained_variance_ratio_.sum())

0.9070055181341605


In [20]:
print(svd.singular_values_)

[1314.4760969  1064.1272996   656.00398368  628.92667465  559.24048697
  485.87707257  468.46729897  421.15565901  369.16360543  330.74921
  306.08963884  275.56072652  273.79010933  263.13249177  253.30419571
  237.9660995   234.12106265  224.66931171  220.68966559  219.74733175
  209.76361193  200.84966496  194.59562741  191.16061457  189.28267441
  185.09767594  181.8398077   177.80910079  175.25373061  172.3712996
  168.71120341  166.35991713  162.54041256  161.93320741  160.89884898
  157.50437655  155.81897526  153.95847281  151.69043618  147.03081873
  146.14815566  144.296469    142.72419481  142.05187744  139.55010722
  137.45716971  135.63208223  133.3095047   132.5003971   130.51977596
  129.99835147  127.97882115  126.51962047  125.64229029  123.93121306
  122.1095116   121.63316247  119.30629459  118.23276598  116.77648349
  115.94802741  115.57049004  115.31490141  114.96799062  112.92591477
  112.29530547  110.87074072  110.20002529  109.05581702  108.3258549
  107.88972

In [21]:
# performing Multinomial Logistic Regression(MLR)

from sklearn.linear_model import LogisticRegression
train_samples = 5000

In [22]:
mlr = LogisticRegression(C=50. / train_samples, penalty='l1', solver='saga', tol=0.1).fit(traindata,trainlabel)

In [23]:
mlr.predict(testdata)

array([0, 1, 2, ..., 8, 8, 2], dtype=int64)

In [24]:
mlr.predict_proba(testdata)

array([[7.59681178e-01, 1.74497026e-04, 6.07845596e-03, ...,
        4.03514310e-05, 4.42441367e-04, 1.27472162e-04],
       [5.01787091e-04, 9.93951903e-01, 1.24206434e-04, ...,
        2.19702090e-05, 8.36629854e-06, 2.33660129e-05],
       [1.51692152e-02, 1.56755147e-02, 5.83400065e-01, ...,
        6.73220814e-03, 8.78985714e-04, 2.16366347e-03],
       ...,
       [1.26395872e-06, 1.41918988e-06, 3.52393701e-05, ...,
        6.79082147e-05, 9.99273773e-01, 4.32967086e-05],
       [4.65293517e-02, 2.48190147e-03, 1.89619426e-02, ...,
        6.52565968e-04, 9.20277146e-01, 1.49838497e-03],
       [9.02259165e-03, 3.44879520e-03, 5.18453239e-01, ...,
        1.23201328e-04, 7.65033297e-04, 5.81849702e-04]])

In [25]:
sparsity = np.mean(mlr.coef_ == 0) * 100
print("Sparsity with L1 penalty: %.2f%%" % sparsity)

Sparsity with L1 penalty: 3.43%


In [26]:
mlr.score(testdata, testlabel)

0.7249

In [27]:
# performing Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [28]:
gnb = GaussianNB()

In [29]:
 gnb.fit(traindata, trainlabel)

GaussianNB()

In [30]:
gnb.score(testdata, testlabel)

0.5597

In [31]:
y_pred = gnb.predict(testdata)
y_pred

array([0, 1, 2, ..., 8, 8, 2], dtype=int64)

In [32]:
y_true = testlabel.ravel()
y_true


array([0, 1, 2, ..., 8, 8, 1], dtype=int64)

In [33]:
accuracy_score(y_true, y_pred)

0.5597

In [34]:
# Performing KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [35]:
# Considering 10% of training dat for validation

(traindata, valdata, trainlabel, vallabel) = train_test_split(traindata, trainlabel,
test_size=0.1, random_state=84)

In [36]:
traindata.shape

(54000, 140)

In [37]:
valdata.shape

(6000, 140)

In [38]:
trainlabel.shape

(54000,)

In [39]:
vallabel.shape

(6000,)

In [40]:
# initializing values of k along with the accuracies

kVals = range(1, 15, 2)
accuracies = []

In [41]:
# Looping values of 'k' for KNN

for k in range(1, 15, 2):
          model = KNeighborsClassifier(n_neighbors=k)
          model.fit(traindata, trainlabel)
          score = model.score(valdata, vallabel)
          print("k=%d, accuracy=%.2f%%" % (k, score * 100))
          accuracies.append(score)

k=1, accuracy=85.25%
k=3, accuracy=86.12%
k=5, accuracy=86.38%
k=7, accuracy=86.58%
k=9, accuracy=86.53%
k=11, accuracy=86.08%
k=13, accuracy=86.25%


In [42]:
# Knowing value of 'k' with highest accuracy

i = np.argmax(accuracies)
print("k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[i],
accuracies[i] * 100))

k=7 achieved highest accuracy of 86.58% on validation data


In [43]:
# With best k-value, predicting the labels of test data

model = KNeighborsClassifier(n_neighbors=kVals[i])
model.fit(traindata, trainlabel)
predictions = model.predict(testdata)


In [44]:
model.score(testdata, testlabel)

0.7245

In [45]:
# final classification report 

print(classification_report(testlabel, predictions))

              precision    recall  f1-score   support

           0       0.71      0.81      0.75      1000
           1       0.98      0.87      0.92      1000
           2       0.63      0.50      0.56      1000
           3       0.76      0.79      0.77      1000
           4       0.56      0.66      0.60      1000
           5       0.93      0.41      0.57      1000
           6       0.50      0.51      0.50      1000
           7       0.64      0.90      0.75      1000
           8       0.95      0.88      0.92      1000
           9       0.80      0.92      0.86      1000

    accuracy                           0.72     10000
   macro avg       0.75      0.72      0.72     10000
weighted avg       0.75      0.72      0.72     10000

