In [1]:
# importing libraries
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler 

In [2]:
#loading train data
fashion_train = pd.read_csv(r"D:\Fall 2020 courses\CSC5825 machine learning\homework\HW3\fashion-mnist_train.csv")
fashion_train.head(5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
#loading test data
fashion_test = pd.read_csv(r"D:\Fall 2020 courses\CSC5825 machine learning\homework\HW3\fashion-mnist_test.csv")
fashion_test.head(5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
# dimensionality of train data
fashion_train.shape

(60000, 785)

In [5]:
# dimensionality of test data
fashion_test.shape

(10000, 785)

In [6]:
# defining features and classes for train data
traindata = fashion_train.iloc[:,1:]
trainlabel = fashion_train.label
label = sorted(trainlabel.unique())

In [7]:
traindata.shape

(60000, 784)

In [8]:
trainlabel.shape

(60000,)

In [9]:
# defining features and classes for test data
testdata = fashion_test.iloc[:,1:]
testlabel = fashion_test.label
label = sorted(testlabel.unique())

In [10]:
testdata.shape

(10000, 784)

In [11]:
testlabel.shape

(10000,)

In [12]:
# performing Multinomial Logistic Regression(MLR)

from sklearn.linear_model import LogisticRegression
train_samples = 5000

In [13]:
mlr = LogisticRegression(C=50. / train_samples, penalty='l1', solver='saga', tol=0.1).fit(traindata,trainlabel)

In [14]:
mlr.predict(testdata)

array([0, 1, 2, ..., 8, 8, 2], dtype=int64)

In [15]:
mlr.predict_proba(testdata)

array([[8.15963667e-01, 9.71683125e-07, 2.84835044e-04, ...,
        2.21950697e-13, 6.27588123e-05, 1.96190576e-13],
       [1.78513342e-05, 9.99847100e-01, 6.75254062e-06, ...,
        6.73056397e-09, 6.24294759e-07, 3.58425531e-09],
       [3.58364238e-02, 1.49764664e-02, 6.91058758e-01, ...,
        2.97277976e-06, 4.45631165e-03, 4.47722829e-05],
       ...,
       [1.59688538e-08, 4.53765147e-08, 4.50710883e-05, ...,
        9.22137469e-09, 9.99489107e-01, 1.44311987e-10],
       [4.89397693e-03, 2.30418812e-06, 2.76774667e-03, ...,
        4.68065038e-12, 7.74651233e-01, 9.26113804e-10],
       [3.09013245e-02, 5.50479318e-02, 6.60519878e-01, ...,
        1.88717873e-13, 3.13646076e-04, 1.07902236e-12]])

In [16]:
sparsity = np.mean(mlr.coef_ == 0) * 100
print("Sparsity with L1 penalty: %.2f%%" % sparsity)

Sparsity with L1 penalty: 2.69%


In [17]:
mlr.score(testdata, testlabel)

0.853

In [18]:
# performing Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [19]:
gnb = GaussianNB()

In [20]:
 gnb.fit(traindata, trainlabel)

GaussianNB()

In [21]:
gnb.score(testdata, testlabel)

0.5914

In [22]:
y_pred = gnb.predict(testdata)
y_pred

array([0, 1, 2, ..., 8, 8, 2], dtype=int64)

In [23]:
y_true = testlabel.ravel()
y_true


array([0, 1, 2, ..., 8, 8, 1], dtype=int64)

In [24]:
accuracy_score(y_true, y_pred)

0.5914

In [25]:
# Performing KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [26]:
# Considering 10% of training dat for validation

(traindata, valdata, trainlabel, vallabel) = train_test_split(traindata, trainlabel,
test_size=0.1, random_state=84)

In [27]:
traindata.shape

(54000, 784)

In [28]:
valdata.shape

(6000, 784)

In [29]:
trainlabel.shape

(54000,)

In [30]:
vallabel.shape

(6000,)

In [31]:
# initializing values of k along with the accuracies

kVals = range(1, 15, 2)
accuracies = []

In [32]:
# Looping values of 'k' for KNN

for k in range(1, 15, 2):
          model = KNeighborsClassifier(n_neighbors=k)
          model.fit(traindata, trainlabel)
          score = model.score(valdata, vallabel)
          print("k=%d, accuracy=%.2f%%" % (k, score * 100))
          accuracies.append(score)

k=1, accuracy=84.68%
k=3, accuracy=85.62%
k=5, accuracy=85.37%
k=7, accuracy=85.73%
k=9, accuracy=85.32%
k=11, accuracy=85.22%
k=13, accuracy=84.83%


In [33]:
# Knowing value of 'k' with highest accuracy

i = np.argmax(accuracies)
print("k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[i],
accuracies[i] * 100))

k=7 achieved highest accuracy of 85.73% on validation data


In [34]:
# With best k-value, predicting the labels of test data

model = KNeighborsClassifier(n_neighbors=kVals[i])
model.fit(traindata, trainlabel)
predictions = model.predict(testdata)


In [35]:
model.score(testdata, testlabel)

0.8523

In [36]:
# final classification report 

print(classification_report(testlabel, predictions))

              precision    recall  f1-score   support

           0       0.76      0.86      0.81      1000
           1       0.99      0.96      0.98      1000
           2       0.75      0.80      0.77      1000
           3       0.92      0.87      0.90      1000
           4       0.79      0.79      0.79      1000
           5       0.99      0.80      0.88      1000
           6       0.65      0.58      0.61      1000
           7       0.86      0.94      0.90      1000
           8       0.97      0.95      0.96      1000
           9       0.88      0.96      0.92      1000

    accuracy                           0.85     10000
   macro avg       0.86      0.85      0.85     10000
weighted avg       0.86      0.85      0.85     10000

